import "./globals.css";
import type { Metadata } from "next";
import { fontPrimary, fontSecondary } from "@/lib/fonts";
import Header from "@/components/ui/header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={`${fontPrimary.variable} ${fontSecondary.variable}`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
